sgv/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('telaPrincipal.urls', namespace='telaPrincipal')),
]

telaPrincipal/urls.py
from . import views
from django.urls import path
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView

app_name = 'telaPrincipal'

urlpatterns = [
    url(r'^$', view=views.index, name='index'),
    url(r'^maquina/(?P<id_maquina>[-\w]+)/(?P<id_estrutura>[-\w]+)/$', view=views.maquina, name='urlMaquina'),
    url(r'^formMaquina', views.formularioMaquina, name='urlFormMaquina'),
    url(r'^FormEstrutura', views.formularioEstrutura, name='urlFormEstrutura'),
    url(r'^ajax/carregarEstruturas/', views.carregarEstruturas, name='ajaxCarregarEstruturas'),
    url(r'^ajax/carregarPrazosEstrutura/', views.carregarPrazosEstrutura, name='ajaxCarregarPrazosEstrutura'),
    url('accounts/login/', auth_views.LoginView.as_view(), name='loginForm'),
    url('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^HourlyScheduleManagement1', views.hourlySchedManag1, name='urlHourlySchedManag1'),
    url(r'^HourlyScheduleManagement2/(?P<local>[-\w]+)/(?P<mes>[-\w]+)/(?P<ano>[-\w]+)/$', views.hourlySchedManag2, name='urlHourlySchedManag2'),
    url(r'^formHourlyScheduleManagement', views.formularioHourlySchedManag, name='urlFormHourlySchedManag'),
    url(r'^hsm', views.formularioHourlySchedManagAdd, name='urlFormHourlySchedManagAdd'),

    url(r'^ajax/carEstrProcHSM/', views.carregarEstrProcHSM, name='ajaxCarEstrProcHSM'),

    url(r'^bc', views.baixarCartao, name='urlBaixarCartao'),
    url(r'^cb/(?P<processo>[-\w]+)/(?P<idestrutura>[-\w]+)/$', views.baixarCartaoSalvar, name='urlBaixarCartaoSalvar'),
]

telaPrincipal/models.py
from django.db import models

# Create your models here.
class Maquinas (models.Model):
    nome = models.CharField(
        max_length=50,
        null=False,
        blank=False
    )
    areaNegocio = models.IntegerField(
        null=False,
        blank=False,
        db_index=True
    )
    def __str__(self):
        return self.nome

class Estruturas (models.Model):
    id_maquinas = models.ForeignKey('Maquinas', on_delete=models.PROTECT)
    nome = models.CharField(
        max_length=50,
        null=False,
        blank=False
    )
    prazopadraocorte = models.IntegerField(
        null=False, blank=False
    )
    prazopadraocaldsolda = models.IntegerField(
        null=False, blank=False
    )
    prazopadraousinagem = models.IntegerField(
        null=False, blank=False
    )
    prazopadraopintura = models.IntegerField(
        null=False, blank=False
    )
    def __str__(self):
        return self.nome

class Maquina (models.Model):
    id_maquinas = models.ForeignKey('Maquinas', on_delete=models.PROTECT)
    serial = models.IntegerField(
        null=False,
        blank=False,
        db_index=True
    )
    def __str__(self):
        return (str(self.id_maquinas.nome) + " - SN: " + str(self.serial))

class Estrutura (models.Model):
    id_maquina = models.ForeignKey('Maquina', on_delete=models.PROTECT)
    id_estruturas = models.ForeignKey('Estruturas', on_delete=models.PROTECT)
    ordemproducao = models.CharField(
        max_length=50,
        null=False,
        blank=False
    )
    prazocorte = models.IntegerField(
        null=False, blank=False
    )
    prazocaldsolda = models.IntegerField(
        null=False, blank=False
    )
    prazousinagem = models.IntegerField(
        null=False, blank=False
    )
    prazopintura = models.IntegerField(
        null=False, blank=False
    )
    dataEntregaMax = models.DateTimeField(null=False)
    dataEntradaSistema = models.DateTimeField(auto_now_add=True)
    dataInicioManufatura = models.DateTimeField(null=False)
    dataBaixaCorte = models.DateTimeField(null=True, blank=True)
    dataBaixaCaldSolda = models.DateTimeField(null=True, blank=True)
    dataBaixaUsinagem = models.DateTimeField(null=True, blank=True)
    dataBaixaPintura = models.DateTimeField(null=True, blank=True)
    dataConfirmEntrega = models.DateTimeField(null=True, blank=True)

class Setores (models.Model):
    nome = models.CharField(
        max_length=50,
        null=False,
        blank=False
    )


class Locais (models.Model):
    id_setor = models.ForeignKey('Setores', on_delete=models.PROTECT)
    nome = models.CharField(
        max_length=50,
        null=False,
        blank=False
    )
    def __str__(self):
        return self.nome

class HourlyScheduleManagement (models.Model):
    id_local = models.ForeignKey('Locais', on_delete=models.PROTECT)
    id_estrutura = models.ForeignKey('Estrutura', on_delete=models.PROTECT)
    diaeHoraEntrada = models.DateTimeField(null=True, blank=True)
    diaeHoraSaida = models.DateTimeField(null=True, blank=True)

class HourlyScheduleManagementRealizado (models.Model):
    id_local = models.ForeignKey('Locais', on_delete=models.PROTECT)
    id_estrutura = models.ForeignKey('Estrutura', on_delete=models.PROTECT)
    diaeHoraEntrada = models.DateTimeField(null=True, blank=True)
    diaeHoraSaida = models.DateTimeField(null=True, blank=True)
    id_usuario = models.IntegerField(null=True, blank=True)

class HSMEmProcesso (models.Model):
    id_local = models.ForeignKey('Locais', on_delete=models.PROTECT)
    id_estrutura = models.ForeignKey('Estrutura', on_delete=models.PROTECT)
    diaeHoraEntrada = models.DateTimeField(null=True, blank=True)
    diaeHoraSaida = models.DateTimeField(null=True, blank=True)
    id_usuario = models.IntegerField(null=False, blank=False)
    id_tarefasgerais = models.ForeignKey('TarefasGerais', null=True, blank=True, on_delete=models.SET_NULL)

class TarefasGerais (models.Model):
    sigla = models.CharField(
        max_length=10,
        null=False,
        blank=False
    )
    nome = models.CharField(
        max_length=50,
        null=False,
        blank=False
    )
    def __str__(self):
        return  (str(self.sigla) + " - " + str(self.nome))

class HSMTarefasGerais (models.Model):
    id_tarefasgerais = models.ForeignKey('TarefasGerais', on_delete=models.PROTECT)
    id_hsmemprocesso = models.ForeignKey('HSMEmProcesso', on_delete=models.SET_NULL, blank=True, null=True)
    id_hsmrealizado = models.ForeignKey('HourlyScheduleManagementRealizado', on_delete=models.SET_NULL, blank=True, null=True)
    diaeHoraInicio = models.DateTimeField(null=True, blank=True)
    diaeHoraFim = models.DateTimeField(null=True, blank=True)

telaPrincipal/views.py
from django.shortcuts import render
from datetime import datetime, timedelta, timezone, date
import datetime
import calendar
from . import models
import pytz
from .forms import FormMaquina
from .forms import FormEstrutura, FormScheduleManagement, FormScheduleManagementAdd, FormHourlySchedManag1
from .models import Estruturas, Maquina, Locais, HSMEmProcesso, HourlyScheduleManagementRealizado, TarefasGerais, HSMTarefasGerais
import math
from django.contrib import messages
import calendar

from django.http import HttpResponseRedirect
from django.urls import reverse

from django.contrib.auth.decorators import login_required

def somadiasuteis(inicio, numdias):
    diasUteis = 0
    n = 0
    if inicio.hour > 12:
        inicio = inicio + timedelta(days = 1)
    for n in range (0, (numdias * 2)):
        if (inicio + timedelta(n)).weekday() != 6:
            diasUteis = diasUteis + 1
        if diasUteis >= numdias:
            break;
    return (inicio + timedelta(days = n))

def subtrairdatas(start, end):
    if start > end:
        return (abs(start - end).days * (-1))
    else:
        return abs(start - end).days

def subtrairdatasuteis (inicio, fim):
    diasUteis = 0
    if inicio < fim:
        if inicio.hour > 12:
            inicio = inicio + timedelta(days = 1)
        for n in range (0, (abs(inicio - fim).days * 2)):
            if (inicio + timedelta(n)).weekday() != 6:
                diasUteis = diasUteis + 1
            if (inicio + timedelta(n)).replace(hour=23, minute=59, second=59, microsecond=0) >= fim.replace(hour=23, minute=59, second=59, microsecond=0):
                break;
        return ((-1) *diasUteis)
    elif fim < inicio:
        if fim.hour > 12:
            fim = fim + timedelta(days = 1)
        for n in range (0, (abs(fim - inicio).days * 2)):
            if (fim + timedelta(n)).weekday() != 6:
                diasUteis = diasUteis + 1
            if (fim + timedelta(n)).replace(hour=23, minute=59, second=59, microsecond=0) >= inicio.replace(hour=23, minute=59, second=59, microsecond=0):
                break;
        return (diasUteis)
    else:
        return (0)

def index(request):
    CONST_NUMDIASNOPRAZO = 10
    CONST_NUMDIASFORADOPRAZO = 5

    def numdedomingos(start, end):
        num = 0
        if start < end:
            for n in range(int ((end - start).days) + 1):
                if (start + timedelta(n)).weekday() == 6:
                    num = num + 1
            return num
        else:
            for n in range(int ((start - end).days) + 1):
                if (end + timedelta(n)).weekday() == 6:
                    num = num + 1
            return num

    def buscarCartoesdosProcessos (b, processo):
        busca = models.Estrutura.objects.raw(b)
        gruposCartoesnoPrazo = []
        for x in range(0, CONST_NUMDIASNOPRAZO):
            gruposCartoesnoPrazo.append([])
        gruposCartoesforadoPrazo = []
        for x in range(0, CONST_NUMDIASFORADOPRAZO):
            gruposCartoesforadoPrazo.append([])

        for b in busca:
            dataPrazoMaxProcesso = somadiasuteis(b.dataInicioProcesso, (b.prazoPadraoProcesso + b.prazoProcesso)).replace(hour=23, minute=59, second=59, microsecond=0)#NÃO MEXER
            print (b.ordemproducao)
            print (b.dataInicioProcesso)
            print (b.dataEntregaMax)
            posicaoGestaoaVista = subtrairdatas(datetime.datetime.now().replace(hour=23, minute=59, second=59, microsecond=0), dataPrazoMaxProcesso)#NÃO MEXER
            if posicaoGestaoaVista >= 0:
                diasNecessarios = subtrairdatasuteis(dataPrazoMaxProcesso, datetime.datetime.now().replace(hour=23, minute=59, second=59, microsecond=0))
            else:
                diasNecessarios = 0
            if processo == "corte":
                diasNecessarios = diasNecessarios + (b.prazopadraocaldsolda + b.prazocaldsolda + b.prazopadraousinagem + b.prazousinagem + b.prazopadraopintura + b.prazopintura)
            elif processo == "caldsolda":
                diasNecessarios = diasNecessarios + (b.prazopadraousinagem + b.prazousinagem + b.prazopadraopintura + b.prazopintura)
            elif processo == "Usinagem":
                diasNecessarios = diasNecessarios + (b.prazopadraopintura + b.prazopintura)
            elif processo == "Pintura":
                diasNecessarios = diasNecessarios

            print (diasNecessarios)

            if datetime.datetime.now() > b.dataInicioProcesso:
                dataEntregaEstimada = somadiasuteis(datetime.datetime.now().replace(hour=0, minute=0, second=0, microsecond=0), diasNecessarios).replace(hour=23, minute=59, second=0, microsecond=0)
            else:
                dataEntregaEstimada = somadiasuteis(b.dataInicioProcesso, diasNecessarios).replace(hour=23, minute=59, second=0, microsecond=0)
            print (dataEntregaEstimada)
            if posicaoGestaoaVista >= 0:
                print ("aqui1")
                diasDisponiveis = subtrairdatasuteis(b.dataEntregaMax.replace(tzinfo=None), dataEntregaEstimada) - 1
            else:
                print ("aqui2")
                diasDisponiveis = subtrairdatas(dataEntregaEstimada, b.dataEntregaMax.replace(tzinfo=None)) - 1
            print (diasDisponiveis)
            if diasDisponiveis >= 0:
                estiloCSSCartaonoPrazodeEntrega = "cartaonoprazodeentrega"
            elif diasDisponiveis > -5:
                estiloCSSCartaonoPrazodeEntrega = "cartaoforadoprazodeentrega1"
            elif diasDisponiveis > -10:
                estiloCSSCartaonoPrazodeEntrega = "cartaoforadoprazodeentrega2"
            else:
                estiloCSSCartaonoPrazodeEntrega = "cartaoforadoprazodeentrega3"

            if posicaoGestaoaVista >= 0 and posicaoGestaoaVista < CONST_NUMDIASNOPRAZO:
                cartoesnoPrazo = gruposCartoesnoPrazo[posicaoGestaoaVista]

                cartoesnoPrazo.append([diasDisponiveis,b, estiloCSSCartaonoPrazodeEntrega])
                gruposCartoesnoPrazo[posicaoGestaoaVista] = cartoesnoPrazo
            elif posicaoGestaoaVista >= CONST_NUMDIASNOPRAZO:
                cartoesnoPrazo = gruposCartoesnoPrazo[-1]
                cartoesnoPrazo.append([diasDisponiveis,b, estiloCSSCartaonoPrazodeEntrega])
                gruposCartoesnoPrazo[-1] = cartoesnoPrazo
            else:
                posicaoGestaoaVista = (posicaoGestaoaVista * (-1))
                if posicaoGestaoaVista < CONST_NUMDIASFORADOPRAZO:
                    cartoesforadoPrazo = gruposCartoesforadoPrazo[posicaoGestaoaVista]
                    cartoesforadoPrazo.append([diasDisponiveis,b, estiloCSSCartaonoPrazodeEntrega])
                    gruposCartoesforadoPrazo[posicaoGestaoaVista] = cartoesforadoPrazo
                else:
                    cartoesforadoPrazo = gruposCartoesforadoPrazo[-1]
                    cartoesforadoPrazo.append([diasDisponiveis,b, estiloCSSCartaonoPrazodeEntrega])
                    gruposCartoesforadoPrazo[-1] = cartoesforadoPrazo

        for x in range(0, CONST_NUMDIASNOPRAZO):
            cartoesnoPrazo = gruposCartoesnoPrazo[x]
            cartoesnoPrazo = sorted(cartoesnoPrazo, key=lambda x: x[0])
            if len(cartoesnoPrazo) < 4:
                for y in range (len(cartoesnoPrazo), 4):
                    cartoesnoPrazo.append(["","empty", ""])
            elif len(cartoesnoPrazo) > 4:
                menorPrazo = 1
                for y in range (3, len(cartoesnoPrazo)):
                    if cartoesnoPrazo[y][0] < menorPrazo:
                        menorPrazo = cartoesnoPrazo[y][0]
                if menorPrazo > 0:
                    estiloCSSCartaonoPrazodeEntrega = "cartaonoprazodeentrega"
                elif menorPrazo > -5:
                    estiloCSSCartaonoPrazodeEntrega = "cartaoforadoprazodeentrega1"
                elif menorPrazo > -10:
                    estiloCSSCartaonoPrazodeEntrega = "cartaoforadoprazodeentrega2"
                else:
                    estiloCSSCartaonoPrazodeEntrega = "cartaoforadoprazodeentrega3"
                cartoesnoPrazo.insert(3, [len(cartoesnoPrazo) - 3, "mais", estiloCSSCartaonoPrazodeEntrega])

            for index, c in enumerate(cartoesnoPrazo):
                c.append(math.ceil((index+1) / 2))
                if ((index+1) % 2 == 0):
                    c.append(2)
                else:
                    c.append(1)
                cartoesnoPrazo[index] = c

            gruposCartoesnoPrazo[x] = cartoesnoPrazo

            if diasnoprazo[x][0].weekday() == 6 and x < (CONST_NUMDIASNOPRAZO - 1):
                gruposCartoesnoPrazo[x] = "domingo"

        for x in range(0, CONST_NUMDIASFORADOPRAZO):
            cartoesforadoPrazo = gruposCartoesforadoPrazo[x]
            cartoesforadoPrazo = sorted(cartoesforadoPrazo, key=lambda x: x[0])
            if len(cartoesforadoPrazo) < 4:
                for y in range (len(cartoesforadoPrazo), 4):
                    cartoesforadoPrazo.append(["empty","empty","empty"])
            elif len(cartoesforadoPrazo) > 4:
                menorPrazo = 1
                for y in range (3, len(cartoesforadoPrazo)):
                    if cartoesforadoPrazo[y][0] < menorPrazo:
                        menorPrazo = cartoesforadoPrazo[y][0]
                if menorPrazo > 0:
                    estiloCSSCartaonoPrazodeEntrega = "cartaonoprazodeentrega"
                elif menorPrazo > -5:
                    estiloCSSCartaonoPrazodeEntrega = "cartaoforadoprazodeentrega1"
                elif menorPrazo > -10:
                    estiloCSSCartaonoPrazodeEntrega = "cartaoforadoprazodeentrega2"
                else:
                    estiloCSSCartaonoPrazodeEntrega = "cartaoforadoprazodeentrega3"
                cartoesforadoPrazo.insert(3, [len(cartoesforadoPrazo) - 3, "mais", estiloCSSCartaonoPrazodeEntrega])

            for index, c in enumerate(cartoesforadoPrazo):
                c.append(math.ceil((index+1) / 2))
                if ((index+1) % 2 == 0):

telaPrincipal/templates/telaPrincipal/estruturas_dropdown_list_options.html
<option value="">---------</option>
{% for e in estruturas %}
<option value="{{ e.id }}">{{ e.nome }}</option>
{% endfor %}

telaPrincipal/templates/telaPrincipal/formEstrutura.html
{% extends 'telaPrincipal/base.html' %}

{% load crispy_forms_tags %}
{% load static %}

{% block title %}Adicionar Cartão{% endblock %}
{% block h1Pagina %}Adicionar Cartão{% endblock %}

{% block breadcrumTextRight %}
  <ol class="breadcrumb text-right">
    <li style="text-transform:none;"><a href="{% url 'telaPrincipal:index' %}">Gestão a Vista</a></li>
    <li class="active" style="text-transform:none;">Adicionar Cartão</li>
  </ol>
{% endblock %}

{% block content %}
        <style>
          .diasPadrao {
            font-weight: bold;
          }
        </style>

        <div class="content mt-3">

          <div class="card">
            <div class="card-header">
                <strong>Inserir Estrutura</strong> <small> (Novo Cartão no Quadro de Gestão a Vista)</small>
            </div>
            <div class="card-body card-block">
              {% if messages %}
                  {% for message in messages %}
                    <div class="alert alert-success" role="alert">{{ message }}</div>
                  {% endfor %}
              {% endif %}
              <form method="POST" id="formEstrutura" dataCarregarEstruturasURL="{% url 'telaPrincipal:ajaxCarregarEstruturas' %}" dataCarregarPrazosEstrutura="{% url 'telaPrincipal:ajaxCarregarPrazosEstrutura' %}" class="form-row">
                {% csrf_token %}
                <div class="col-md-6">
                  {{ form.id_maquina|as_crispy_field }}
                </div>
                <div class="col-md-6">
                  {{ form.id_estruturas|as_crispy_field }}
                </div>
                <div class="col-md-6">
                  {{ form.ordemproducao|as_crispy_field }}
                </div>
                <div class="form-group col-md-6"></div>
                <div class="form-group col-md-6" >
                  {{ form.dataInicioManufatura|as_crispy_field }}
                </div>
                <div class="form-group col-md-6">
                  {{ form.dataEntregaMax|as_crispy_field }}
                </div>
                <div class="form-group col-md-2">
                  <label class="col-form-label">Prazo Padrão Corte:</label>
                  <div>
                    <span id ="spanPrazoPadraoCorte" class="diasPadrao">-</span> dias
                  </div>
                </div>
                <div class="form-group col-md-2">
                  {{ form.prazocorte|as_crispy_field }}
                </div>
                <div class="form-group col-md-2">
                  <label class="col-form-label">Total Corte:</label>
                  <div>
                  = <span id ="spanTotalPrazoCorte" class="diasPadrao">-</span> dias
                  </div>
                </div>
                <div class="form-group col-md-2">
                  <label class="col-form-label">Prazo Padrão Cald/Solda:</label>
                  <div>
                    <span id ="spanPrazoPadraoCaldSolda" class="diasPadrao">-</span> dias
                  </div>
                </div>
                <div class="form-group col-md-2">
                  {{ form.prazocaldsolda|as_crispy_field }}
                </div>
                <div class="form-group col-md-2">
                  <label class="col-form-label">Total Cald/Solda:</label>
                  <div>
                  = <span id ="spanTotalCaldSolda" class="diasPadrao">-</span> dias
                  </div>
                </div>
                <div class="form-group col-md-2">
                  <label class="col-form-label">Prazo Padrão Usinagem:</label>
                  <div>
                    <span id ="spanPrazoPadraoUsinagem" class="diasPadrao">-</span> dias
                  </div>
                </div>
                <div class="form-group col-md-2">
                  {{ form.prazousinagem|as_crispy_field }}
                </div>
                <div class="form-group col-md-2">
                  <label class="col-form-label">Total Usinagem:</label>
                  <div>
                  = <span id ="spanTotalUsinagem" class="diasPadrao">-</span> dias
                  </div>
                </div>
                <div class="form-group col-md-2">
                  <label class="col-form-label">Prazo Padrão Pintura:</label>
                  <div>
                    <span id ="spanPrazoPadraoPintura" class="diasPadrao">-</span> dias
                  </div>
                </div>
                <div class="form-group col-md-2">
                  {{ form.prazopintura|as_crispy_field }}
                </div>
                <div class="form-group col-md-2">
                  <label class="col-form-label">Total Pintura:</label>
                  <div>
                  = <span id ="spanTotalPintura" class="diasPadrao">-</span> dias
                  </div>
                </div>
                <div class="col-6 text-center"><a href="../" class="btn btn-warning">Cancelar</a></div>
                <div class="col-6 text-center"><button type="submit" class="btn btn-info">Salvar</button></div>
              </form>
            </div>
          </div>
        </div> <!-- .content -->
{% endblock %}

{% block arquivosJS %}
  <script type="text/javascript">
    jQuery(document).ready(function($) {
      $("#id_id_maquina").change(function () {
        var url = $("#formEstrutura").attr("dataCarregarEstruturasURL");  // get the url of the `load_cities` view
        var idMaquina = $(this).val();  // get the selected country ID from the HTML input
        $.ajax({                       // initialize an AJAX request
          cache: false,
          contentType: "application/html; charset=utf-8",
          url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
          data: {
            'id_maquina': idMaquina       // add the country id to the GET parameters
          },
          success: function (data) {   // `data` is the return of the `load_cities` view function
            $("#id_id_estruturas").html(data);  // replace the contents of the city input with the data that came from the server
            $("#spanPrazoPadraoCorte").html("-");
            $("#spanTotalPrazoCorte").html("-");
            $("#spanPrazoPadraoCaldSolda").html("-");
            $("#spanTotalCaldSolda").html("-");
            $("#spanPrazoPadraoUsinagem").html("-");
            $("#spanTotalUsinagem").html("-");
            $("#spanPrazoPadraoPintura").html("-");
            $("#spanTotalPintura").html("-");
          }
        });
      });

      $("#id_id_estruturas").change(function () {
        var url = $("#formEstrutura").attr("dataCarregarPrazosEstrutura");  // get the url of the `load_cities` view
        var id_estrutura = $(this).val();  // get the selected country ID from the HTML input
        $.ajax({                       // initialize an AJAX request
          cache: false,
          contentType: "application/json; charset=utf-8",
          dataType: "json",
          url: url,
          data: {
            'id_estrutura': id_estrutura
          }
        })
        .done(function (response) {
          $.each(response, function (index, value) {
            $("#spanPrazoPadraoCorte").html(this.prazopadraocorte);
            $("#spanTotalPrazoCorte").html(Number(this.prazopadraocorte) + Number($("#id_prazocorte").val()));
            $("#spanPrazoPadraoCaldSolda").html(this.prazopadraocaldsolda);
            $("#spanTotalCaldSolda").html(Number(this.prazopadraocaldsolda) + Number($("#id_prazocaldsolda").val()));
            $("#spanPrazoPadraoUsinagem").html(this.prazopadraousinagem);
            $("#spanTotalUsinagem").html(Number(this.prazopadraousinagem) + Number($("#id_prazousinagem").val()));
            $("#spanPrazoPadraoPintura").html(this.prazopadraopintura);
            $("#spanTotalPintura").html(Number(this.prazopadraopintura) + Number($("#id_prazopintura").val()));
          })
        })
        ;
      });

      $("#id_prazocorte").change(function () {
        $("#spanTotalPrazoCorte").html(Number($("#spanPrazoPadraoCorte").text()) + Number($(this).val()));
      });
      $( "#id_prazocorte" ).addClass("form-control-sm");

      $("#id_prazocaldsolda").change(function () {
        $("#spanTotalCaldSolda").html(Number($("#spanPrazoPadraoCaldSolda").text()) + Number($(this).val()));
      });
      $( "#id_prazocaldsolda" ).addClass("form-control-sm");

      $("#id_prazousinagem").change(function () {
        $("#spanTotalUsinagem").html(Number($("#spanPrazoPadraoUsinagem").text()) + Number($(this).val()));
      });
      $( "#id_prazousinagem" ).addClass("form-control-sm");

      $("#id_prazopintura").change(function () {
        $("#spanTotalPintura").html(Number($("#spanPrazoPadraoPintura").text()) + Number($(this).val()));
      });
      $( "#id_prazopintura" ).addClass("form-control-sm");

      jQuery.datetimepicker.setLocale('pt-BR');
      $('#id_dataInicioManufatura').disableAutoFill();
      $("#id_dataInicioManufatura").datetimepicker({
        format:'d/m/Y H:i',
        allowTimes:[
          '00:00', '00:30',
          '01:00', '01:30',
          '02:00', '02:30',
          '03:00', '03:30',
          '04:00', '04:30',
          '05:00', '05:30',
          '06:00', '06:30',
          '07:00', '07:30',
          '08:00', '08:30',
          '09:00', '09:30',
          '10:00', '10:30',
          '11:00', '11:30',
          '12:00', '12:30',
          '13:00', '13:30',
          '14:00', '14:30',
          '15:00', '15:30',
          '16:00', '16:30',
          '17:00', '17:30',
          '18:00', '18:30',
          '19:00', '19:30',
          '20:00', '20:30',
          '21:00', '21:30',
          '22:00', '22:30',
          '23:00', '23:30'
         ]
      });
      $('#id_dataEntregaMax').disableAutoFill();
      $("#id_dataEntregaMax").datetimepicker({
        format:'d/m/Y H:i',
        allowTimes:[
          '00:00', '00:30',
          '01:00', '01:30',
          '02:00', '02:30',
          '03:00', '03:30',
          '04:00', '04:30',
          '05:00', '05:30',
          '06:00', '06:30',
          '07:00', '07:30',
          '08:00', '08:30',
          '09:00', '09:30',
          '10:00', '10:30',
          '11:00', '11:30',
          '12:00', '12:30',
          '13:00', '13:30',
          '14:00', '14:30',
          '15:00', '15:30',
          '16:00', '16:30',
          '17:00', '17:30',
          '18:00', '18:30',
          '19:00', '19:30',
          '20:00', '20:30',
          '21:00', '21:30',
          '22:00', '22:30',
          '23:00', '23:30'
         ]
      });
    });
  </script>
{% endblock %}